name: Docs build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install mkdocs==1.6.0 mkdocs-material==9.5.27
      - run: mkdocs gh-deploy --config-file ./docs/mkdocs.yml --force --clean --verbose